overrides:
  '@babel/core': 7.29.6
  postcss: 8.5.15
  tmp: ^0.2.7

confirmModulesPurge: false

allowBuilds:
  '@swc/core': true
  core-js: false
  esbuild: true
  puppeteer: true
  sharp: true
  unrs-resolver: true
