#!/usr/bin/env ts-node
import * as XLSX from 'xlsx';
import * as fs from 'fs';
import * as path from 'path';
import { Scale, Timetable, TimetableAct, TimetableDay, Weekday } from '../src/components/camp/timetable/types';
import { getCamp2026ParticipantsKo } from '../src/data/camps';

const SCALE_MAP: Record<string, Scale> = {
  '솔로/듀오': 'solo',
  '밴드(1인)': 'solo',
  '밴드(2인)': 'solo',
  '밴드(3-4인)': 'band',
  '밴드(5인+)': 'big-band',
  '밴드(다수)': 'ensemble',
};

export function mapScale(raw: string): Scale | undefined {
  return SCALE_MAP[raw.trim()];
}

export function normalizeName(raw: string): string {
  return raw.trim().replace(/\s+/g, ' ');
}

export function parseTransitionMinutes(raw: string): number | null {
  const match = raw.match(/⟶\s*(\d+)\s*분/);
  return match ? Number(match[1]) : null;
}

function parseNextActName(raw: string): string | undefined {
  const match = raw.match(/다음:\s*([^-()]+)\s*-/);
  return match && match[1] ? match[1].trim() : undefined;
}

type RawRow = (string | number | null | undefined)[];

export function parseRow(row: RawRow, nameToId: Map<string, number>): TimetableAct | null {
  const [, orderRaw, start, end, kind, name, , scaleRaw] = row;

  if (!start || !end || !kind || !name) return null;

  if (kind === '전환') {
    return {
      order: null,
      start: String(start),
      end: String(end),
      type: 'transition',
      name: String(name),
      transitionMinutes: parseTransitionMinutes(String(name)) ?? undefined,
      nextActName: parseNextActName(String(name)),
    };
  }

  if (kind === '공연') {
    const normalized = normalizeName(String(name));
    const id = nameToId.get(normalized);
    const scale = scaleRaw ? mapScale(String(scaleRaw)) : undefined;

    const act: TimetableAct = {
      order: typeof orderRaw === 'number' ? orderRaw : Number(orderRaw),
      start: String(start),
      end: String(end),
      type: 'performance',
      name: normalized,
    };

    if (scale) act.scale = scale;
    if (id !== undefined) act.musicianIds = [id];

    return act;
  }

  return null;
}

// 엑셀 표기와 camps.ts(ko) 표기가 다른 경우의 수동 매핑
// key: 엑셀의 원본 이름, value: camps.ts(ko)의 canonical 이름
const NAME_OVERRIDES: Record<string, string> = {
  '블로꾸자파리/뽈레뽈레/북짝북짝': '블로꾸 자파리 X 뽈레뽈레 X 북짝북짝',
  '머티리얼즈 파운드': 'Materials Pound',
  '사바하': 'Sabbaha',
  '메리디에스': 'Meridies',
  '도그라스트페이지': 'Dog Last Page',
  '허니위스키': 'Honey Whiskey',
  'Dear arcadian': 'Dear Arcadian',
  '레인보우99': 'Rainbow99',
  '사이트 with 제트싸이져': 'Sight X Zsthyger',
  '지누콘다': 'Jinu Konda',
};

const DAY_META: Record<string, { date: string; weekday: Weekday; dayLabel: string }> = {
  '6월5일(금)': { date: '2026-06-05', weekday: 'fri', dayLabel: '6/5 (금)' },
  '6월6일(토)': { date: '2026-06-06', weekday: 'sat', dayLabel: '6/6 (토)' },
  '6월7일(일)': { date: '2026-06-07', weekday: 'sun', dayLabel: '6/7 (일)' },
};

function buildNameToIdMap(): Map<string, number> {
  const map = new Map<string, number>();
  for (const p of getCamp2026ParticipantsKo()) {
    if (p.musicianId !== undefined) {
      map.set(normalizeName(p.name), p.musicianId);
    }
  }
  // override 적용: 엑셀 이름 → camps.ts 이름 → id
  for (const [xlsxName, campsName] of Object.entries(NAME_OVERRIDES)) {
    const id = map.get(normalizeName(campsName));
    if (id !== undefined) {
      map.set(normalizeName(xlsxName), id);
    }
  }
  return map;
}

function parseSheet(sheet: XLSX.WorkSheet, nameToId: Map<string, number>): Array<NonNullable<ReturnType<typeof parseRow>>> {
  const rows = XLSX.utils.sheet_to_json<RawRow>(sheet, { header: 1, defval: null });
  // 첫 줄은 헤더, 나머지만 파싱
  return rows.slice(1)
    .map((row) => parseRow(row, nameToId))
    .filter((a): a is NonNullable<typeof a> => a !== null);
}

function convertTimetable(xlsxPath: string): Timetable {
  const workbook = XLSX.readFile(xlsxPath);
  const nameToId = buildNameToIdMap();

  const days: TimetableDay[] = [];

  for (const sheetName of workbook.SheetNames) {
    const meta = DAY_META[sheetName];
    if (!meta) continue;
    const sheet = workbook.Sheets[sheetName];
    if (!sheet) continue;

    const acts = parseSheet(sheet, nameToId);
    const performances = acts.filter((a) => a.type === 'performance');

    days.push({
      date: meta.date,
      dayLabel: meta.dayLabel,
      weekday: meta.weekday,
      teamCount: performances.length,
      startTime: acts[0]?.start ?? '',
      endTime: acts[acts.length - 1]?.end ?? '',
      acts,
    });
  }

  return { year: 2026, days };
}

function writeOutput(data: Timetable, outPath: string): void {
  const header = `// AUTO-GENERATED by scripts/convert-timetable.ts — do not edit manually\n`;
  const body = `import type { Timetable } from '../components/camp/timetable/types';\n\nexport const timetable2026: Timetable = ${JSON.stringify(data, null, 2)};\n`;
  fs.writeFileSync(outPath, header + body, 'utf-8');
}

// Entry point
if (require.main === module) {
  const xlsxPath = path.resolve(__dirname, '../docs/2026캠프 운영/timetable_v5.xlsx');
  const outPath = path.resolve(__dirname, '../src/data/timetable-2026.ts');

  if (!fs.existsSync(xlsxPath)) {
    console.error(`❌ Excel not found: ${xlsxPath}`);
    process.exit(1);
  }

  const data = convertTimetable(xlsxPath);
  writeOutput(data, outPath);

  const totalTeams = data.days.reduce((n, d) => n + d.teamCount, 0);
  console.log(`✅ Converted: ${data.days.length} days, ${totalTeams} teams`);
}
