// AUTO-GENERATED by scripts/convert-timetable.ts — do not edit manually
import type { Timetable } from '../components/camp/timetable/types';

export const timetable2026: Timetable = {
  "year": 2026,
  "days": [
    {
      "date": "2026-06-05",
      "dayLabel": "6/5 (금)",
      "weekday": "fri",
      "teamCount": 12,
      "startTime": "17:00",
      "endTime": "22:57",
      "acts": [
        {
          "order": 1,
          "start": "17:00",
          "end": "17:25",
          "type": "performance",
          "name": "블로꾸자파리/뽈레뽈레/북짝북짝",
          "scale": "ensemble",
          "musicianIds": [
            13
          ]
        },
        {
          "order": null,
          "start": "17:25",
          "end": "17:30",
          "type": "transition",
          "name": "⟶ 5분 (다음: 최상돈 × 김강곤 - 솔로/듀오)",
          "transitionMinutes": 5,
          "nextActName": "최상돈 × 김강곤"
        },
        {
          "order": 2,
          "start": "17:30",
          "end": "17:55",
          "type": "performance",
          "name": "최상돈 × 김강곤",
          "scale": "solo",
          "musicianIds": [
            48
          ]
        },
        {
          "order": null,
          "start": "17:55",
          "end": "18:00",
          "type": "transition",
          "name": "⟶ 5분 (다음: 윤선애 - 솔로/듀오)",
          "transitionMinutes": 5,
          "nextActName": "윤선애"
        },
        {
          "order": 3,
          "start": "18:00",
          "end": "18:25",
          "type": "performance",
          "name": "윤선애",
          "scale": "solo",
          "musicianIds": [
            40
          ]
        },
        {
          "order": null,
          "start": "18:25",
          "end": "18:30",
          "type": "transition",
          "name": "⟶ 5분 (다음: HANASH - 솔로/듀오)",
          "transitionMinutes": 5,
          "nextActName": "HANASH"
        },
        {
          "order": 4,
          "start": "18:30",
          "end": "18:55",
          "type": "performance",
          "name": "HANASH",
          "scale": "solo",
          "musicianIds": [
            59
          ]
        },
        {
          "order": null,
          "start": "18:55",
          "end": "19:00",
          "type": "transition",
          "name": "⟶ 5분 (다음: 나무꾼민건 - 솔로/듀오)",
          "transitionMinutes": 5,
          "nextActName": "나무꾼민건"
        },
        {
          "order": 5,
          "start": "19:00",
          "end": "19:25",
          "type": "performance",
          "name": "나무꾼민건",
          "scale": "solo",
          "musicianIds": [
            17
          ]
        },
        {
          "order": null,
          "start": "19:25",
          "end": "19:30",
          "type": "transition",
          "name": "⟶ 5분 (다음: 키타와 올겐 - 솔로/듀오)",
          "transitionMinutes": 5,
          "nextActName": "키타와 올겐"
        },
        {
          "order": 6,
          "start": "19:30",
          "end": "19:55",
          "type": "performance",
          "name": "키타와 올겐",
          "scale": "solo",
          "musicianIds": [
            50
          ]
        },
        {
          "order": null,
          "start": "19:55",
          "end": "20:00",
          "type": "transition",
          "name": "⟶ 5분 (다음: 손지연 - 솔로/듀오)",
          "transitionMinutes": 5,
          "nextActName": "손지연"
        },
        {
          "order": 7,
          "start": "20:00",
          "end": "20:25",
          "type": "performance",
          "name": "손지연",
          "scale": "solo",
          "musicianIds": [
            30
          ]
        },
        {
          "order": null,
          "start": "20:25",
          "end": "20:30",
          "type": "transition",
          "name": "⟶ 5분 (다음: 여울 - 솔로/듀오)",
          "transitionMinutes": 5,
          "nextActName": "여울"
        },
        {
          "order": 8,
          "start": "20:30",
          "end": "20:55",
          "type": "performance",
          "name": "여울",
          "scale": "solo",
          "musicianIds": [
            38
          ]
        },
        {
          "order": null,
          "start": "20:55",
          "end": "21:00",
          "type": "transition",
          "name": "⟶ 5분 (다음: 모레도토요일 - 솔로/듀오)",
          "transitionMinutes": 5,
          "nextActName": "모레도토요일"
        },
        {
          "order": 9,
          "start": "21:00",
          "end": "21:25",
          "type": "performance",
          "name": "모레도토요일",
          "scale": "solo",
          "musicianIds": [
            7
          ]
        },
        {
          "order": null,
          "start": "21:25",
          "end": "21:30",
          "type": "transition",
          "name": "⟶ 5분 (다음: 찬 - 솔로/듀오)",
          "transitionMinutes": 5,
          "nextActName": "찬"
        },
        {
          "order": 10,
          "start": "21:30",
          "end": "21:55",
          "type": "performance",
          "name": "찬",
          "scale": "solo",
          "musicianIds": [
            47
          ]
        },
        {
          "order": null,
          "start": "21:55",
          "end": "22:00",
          "type": "transition",
          "name": "⟶ 5분 (다음: 모허 - 솔로/듀오)",
          "transitionMinutes": 5,
          "nextActName": "모허"
        },
        {
          "order": 11,
          "start": "22:00",
          "end": "22:25",
          "type": "performance",
          "name": "모허",
          "scale": "solo",
          "musicianIds": [
            22
          ]
        },
        {
          "order": null,
          "start": "22:25",
          "end": "22:32",
          "type": "transition",
          "name": "⟶ 7분 (다음: 태히언 - 중형밴드)",
          "transitionMinutes": 7,
          "nextActName": "태히언"
        },
        {
          "order": 12,
          "start": "22:32",
          "end": "22:57",
          "type": "performance",
          "name": "태히언",
          "scale": "band",
          "musicianIds": [
            51
          ]
        }
      ]
    },
    {
      "date": "2026-06-06",
      "dayLabel": "6/6 (토)",
      "weekday": "sat",
      "teamCount": 20,
      "startTime": "12:00",
      "endTime": "22:37",
      "acts": [
        {
          "order": 1,
          "start": "12:00",
          "end": "12:25",
          "type": "performance",
          "name": "뺄라지다 X 동백작은학교",
          "scale": "ensemble",
          "musicianIds": [
            58
          ]
        },
        {
          "order": null,
          "start": "12:25",
          "end": "12:30",
          "type": "transition",
          "name": "⟶ 5분 (다음: 메리디에스 - 솔로/듀오)",
          "transitionMinutes": 5,
          "nextActName": "메리디에스"
        },
        {
          "order": 2,
          "start": "12:30",
          "end": "12:55",
          "type": "performance",
          "name": "메리디에스",
          "scale": "solo",
          "musicianIds": [
            21
          ]
        },
        {
          "order": null,
          "start": "12:55",
          "end": "13:05",
          "type": "transition",
          "name": "⟶ 10분 (다음: Dear arcadian - 대형밴드)",
          "transitionMinutes": 10,
          "nextActName": "Dear arcadian"
        },
        {
          "order": 3,
          "start": "13:05",
          "end": "13:30",
          "type": "performance",
          "name": "Dear arcadian",
          "scale": "big-band",
          "musicianIds": [
            18
          ]
        },
        {
          "order": null,
          "start": "13:30",
          "end": "13:37",
          "type": "transition",
          "name": "⟶ 7분 (다음: 사바하 - 중형밴드)",
          "transitionMinutes": 7,
          "nextActName": "사바하"
        },
        {
          "order": 4,
          "start": "13:37",
          "end": "14:02",
          "type": "performance",
          "name": "사바하",
          "scale": "band",
          "musicianIds": [
            26
          ]
        },
        {
          "order": null,
          "start": "14:02",
          "end": "14:12",
          "type": "transition",
          "name": "⟶ 10분 (다음: 머티리얼즈 파운드 - 대형밴드)",
          "transitionMinutes": 10,
          "nextActName": "머티리얼즈 파운드"
        },
        {
          "order": 5,
          "start": "14:12",
          "end": "14:37",
          "type": "performance",
          "name": "머티리얼즈 파운드",
          "scale": "big-band",
          "musicianIds": [
            24
          ]
        },
        {
          "order": null,
          "start": "14:37",
          "end": "15:22",
          "type": "transition",
          "name": "⟶ 45분 (다음: 허니위스키 - 대형밴드 여유세팅)",
          "transitionMinutes": 45,
          "nextActName": "허니위스키"
        },
        {
          "order": 6,
          "start": "15:22",
          "end": "15:47",
          "type": "performance",
          "name": "허니위스키",
          "scale": "big-band",
          "musicianIds": [
            54
          ]
        },
        {
          "order": null,
          "start": "15:47",
          "end": "15:52",
          "type": "transition",
          "name": "⟶ 5분 (다음: 이서영 - 솔로/듀오)",
          "transitionMinutes": 5,
          "nextActName": "이서영"
        },
        {
          "order": 7,
          "start": "15:52",
          "end": "16:17",
          "type": "performance",
          "name": "이서영",
          "scale": "solo",
          "musicianIds": [
            12
          ]
        },
        {
          "order": null,
          "start": "16:17",
          "end": "16:22",
          "type": "transition",
          "name": "⟶ 5분 (다음: 길가는밴드 장현호 - 솔로/듀오)",
          "transitionMinutes": 5,
          "nextActName": "길가는밴드 장현호"
        },
        {
          "order": 8,
          "start": "16:22",
          "end": "16:47",
          "type": "performance",
          "name": "길가는밴드 장현호",
          "scale": "solo",
          "musicianIds": [
            15
          ]
        },
        {
          "order": null,
          "start": "16:47",
          "end": "16:52",
          "type": "transition",
          "name": "⟶ 5분 (다음: 윤숭 - 솔로/듀오)",
          "transitionMinutes": 5,
          "nextActName": "윤숭"
        },
        {
          "order": 9,
          "start": "16:52",
          "end": "17:17",
          "type": "performance",
          "name": "윤숭",
          "scale": "solo",
          "musicianIds": [
            39
          ]
        },
        {
          "order": null,
          "start": "17:17",
          "end": "17:22",
          "type": "transition",
          "name": "⟶ 5분 (다음: 조약골 - 솔로/듀오)",
          "transitionMinutes": 5,
          "nextActName": "조약골"
        },
        {
          "order": 10,
          "start": "17:22",
          "end": "17:47",
          "type": "performance",
          "name": "조약골",
          "scale": "solo",
          "musicianIds": [
            44
          ]
        },
        {
          "order": null,
          "start": "17:47",
          "end": "17:52",
          "type": "transition",
          "name": "⟶ 5분 (다음: 지누콘다 - 솔로/듀오)",
          "transitionMinutes": 5,
          "nextActName": "지누콘다"
        },
        {
          "order": 11,
          "start": "17:52",
          "end": "18:17",
          "type": "performance",
          "name": "지누콘다",
          "scale": "solo",
          "musicianIds": [
            46
          ]
        },
        {
          "order": null,
          "start": "18:17",
          "end": "18:22",
          "type": "transition",
          "name": "⟶ 5분 (다음: 호와호 - 솔로/듀오)",
          "transitionMinutes": 5,
          "nextActName": "호와호"
        },
        {
          "order": 12,
          "start": "18:22",
          "end": "18:47",
          "type": "performance",
          "name": "호와호",
          "scale": "solo",
          "musicianIds": [
            53
          ]
        },
        {
          "order": null,
          "start": "18:47",
          "end": "18:52",
          "type": "transition",
          "name": "⟶ 5분 (다음: 안티스트레스 - 솔로/듀오)",
          "transitionMinutes": 5,
          "nextActName": "안티스트레스"
        },
        {
          "order": 13,
          "start": "18:52",
          "end": "19:17",
          "type": "performance",
          "name": "안티스트레스",
          "scale": "solo",
          "musicianIds": [
            35
          ]
        },
        {
          "order": null,
          "start": "19:17",
          "end": "19:22",
          "type": "transition",
          "name": "⟶ 5분 (다음: 손현숙 - 솔로/듀오)",
          "transitionMinutes": 5,
          "nextActName": "손현숙"
        },
        {
          "order": 14,
          "start": "19:22",
          "end": "19:47",
          "type": "performance",
          "name": "손현숙",
          "scale": "solo",
          "musicianIds": [
            31
          ]
        },
        {
          "order": null,
          "start": "19:47",
          "end": "19:52",
          "type": "transition",
          "name": "⟶ 5분 (다음: 모모 - 솔로/듀오)",
          "transitionMinutes": 5,
          "nextActName": "모모"
        },
        {
          "order": 15,
          "start": "19:52",
          "end": "20:17",
          "type": "performance",
          "name": "모모",
          "scale": "solo",
          "musicianIds": [
            10
          ]
        },
        {
          "order": null,
          "start": "20:17",
          "end": "20:22",
          "type": "transition",
          "name": "⟶ 5분 (다음: 송인효 - 솔로/듀오)",
          "transitionMinutes": 5,
          "nextActName": "송인효"
        },
        {
          "order": 16,
          "start": "20:22",
          "end": "20:47",
          "type": "performance",
          "name": "송인효",
          "scale": "solo",
          "musicianIds": [
            33
          ]
        },
        {
          "order": null,
          "start": "20:47",
          "end": "20:52",
          "type": "transition",
          "name": "⟶ 5분 (다음: 송인상 - 솔로/듀오)",
          "transitionMinutes": 5,
          "nextActName": "송인상"
        },
        {
          "order": 17,
          "start": "20:52",
          "end": "21:07",
          "type": "performance",
          "name": "송인상",
          "scale": "solo",
          "musicianIds": [
            32
          ]
        },
        {
          "order": null,
          "start": "21:07",
          "end": "21:12",
          "type": "transition",
          "name": "⟶ 5분 (다음: 허정혁 - 솔로/듀오)",
          "transitionMinutes": 5,
          "nextActName": "허정혁"
        },
        {
          "order": 18,
          "start": "21:12",
          "end": "21:37",
          "type": "performance",
          "name": "허정혁",
          "scale": "solo",
          "musicianIds": [
            55
          ]
        },
        {
          "order": null,
          "start": "21:37",
          "end": "21:42",
          "type": "transition",
          "name": "⟶ 5분 (다음: 피움 - 솔로/듀오)",
          "transitionMinutes": 5,
          "nextActName": "피움"
        },
        {
          "order": 19,
          "start": "21:42",
          "end": "22:07",
          "type": "performance",
          "name": "피움",
          "scale": "solo",
          "musicianIds": [
            52
          ]
        },
        {
          "order": null,
          "start": "22:07",
          "end": "22:12",
          "type": "transition",
          "name": "⟶ 5분 (다음: 강가히말라야 - 솔로/듀오)",
          "transitionMinutes": 5,
          "nextActName": "강가히말라야"
        },
        {
          "order": 20,
          "start": "22:12",
          "end": "22:37",
          "type": "performance",
          "name": "강가히말라야",
          "scale": "solo",
          "musicianIds": [
            14
          ]
        }
      ]
    },
    {
      "date": "2026-06-07",
      "dayLabel": "6/7 (일)",
      "weekday": "sun",
      "teamCount": 20,
      "startTime": "11:00",
      "endTime": "21:00",
      "acts": [
        {
          "order": 1,
          "start": "11:00",
          "end": "11:25",
          "type": "performance",
          "name": "하주원",
          "scale": "solo",
          "musicianIds": [
            57
          ]
        },
        {
          "order": null,
          "start": "11:25",
          "end": "11:30",
          "type": "transition",
          "name": "⟶ 5분 (다음: 선경 - 솔로/듀오)",
          "transitionMinutes": 5,
          "nextActName": "선경"
        },
        {
          "order": 2,
          "start": "11:30",
          "end": "11:55",
          "type": "performance",
          "name": "선경",
          "scale": "solo",
          "musicianIds": [
            29
          ]
        },
        {
          "order": null,
          "start": "11:55",
          "end": "12:00",
          "type": "transition",
          "name": "⟶ 5분 (다음: Joon Lee - 솔로/듀오)",
          "transitionMinutes": 5,
          "nextActName": "Joon Lee"
        },
        {
          "order": 3,
          "start": "12:00",
          "end": "12:25",
          "type": "performance",
          "name": "Joon Lee",
          "scale": "solo",
          "musicianIds": [
            43
          ]
        },
        {
          "order": null,
          "start": "12:25",
          "end": "12:30",
          "type": "transition",
          "name": "⟶ 5분 (다음: 오재환 - 솔로/듀오)",
          "transitionMinutes": 5,
          "nextActName": "오재환"
        },
        {
          "order": 4,
          "start": "12:30",
          "end": "12:55",
          "type": "performance",
          "name": "오재환",
          "scale": "solo",
          "musicianIds": [
            36
          ]
        },
        {
          "order": null,
          "start": "12:55",
          "end": "13:00",
          "type": "transition",
          "name": "⟶ 5분 (다음: 불가사리 즉흥세션 - 솔로/듀오)",
          "transitionMinutes": 5,
          "nextActName": "불가사리 즉흥세션"
        },
        {
          "order": 5,
          "start": "13:00",
          "end": "13:25",
          "type": "performance",
          "name": "불가사리 즉흥세션",
          "scale": "solo",
          "musicianIds": [
            25
          ]
        },
        {
          "order": null,
          "start": "13:25",
          "end": "13:30",
          "type": "transition",
          "name": "⟶ 5분 (다음: 온가영 - 솔로/듀오)",
          "transitionMinutes": 5,
          "nextActName": "온가영"
        },
        {
          "order": 6,
          "start": "13:30",
          "end": "13:55",
          "type": "performance",
          "name": "온가영",
          "scale": "solo",
          "musicianIds": [
            37
          ]
        },
        {
          "order": null,
          "start": "13:55",
          "end": "14:00",
          "type": "transition",
          "name": "⟶ 5분 (다음: 남수 - 솔로/듀오)",
          "transitionMinutes": 5,
          "nextActName": "남수"
        },
        {
          "order": 7,
          "start": "14:00",
          "end": "14:25",
          "type": "performance",
          "name": "남수",
          "scale": "solo",
          "musicianIds": [
            4
          ]
        },
        {
          "order": null,
          "start": "14:25",
          "end": "14:30",
          "type": "transition",
          "name": "⟶ 5분 (다음: 임정득 - 솔로/듀오)",
          "transitionMinutes": 5,
          "nextActName": "임정득"
        },
        {
          "order": 8,
          "start": "14:30",
          "end": "14:55",
          "type": "performance",
          "name": "임정득",
          "scale": "solo",
          "musicianIds": [
            42
          ]
        },
        {
          "order": null,
          "start": "14:55",
          "end": "15:00",
          "type": "transition",
          "name": "⟶ 5분 (다음: 뮁 - 솔로/듀오)",
          "transitionMinutes": 5,
          "nextActName": "뮁"
        },
        {
          "order": 9,
          "start": "15:00",
          "end": "15:25",
          "type": "performance",
          "name": "뮁",
          "scale": "solo",
          "musicianIds": [
            23
          ]
        },
        {
          "order": null,
          "start": "15:25",
          "end": "15:30",
          "type": "transition",
          "name": "⟶ 5분 (다음: 사이트 with 제트싸이져 - 솔로/듀오)",
          "transitionMinutes": 5,
          "nextActName": "사이트 with 제트싸이져"
        },
        {
          "order": 10,
          "start": "15:30",
          "end": "15:55",
          "type": "performance",
          "name": "사이트 with 제트싸이져",
          "scale": "solo",
          "musicianIds": [
            27
          ]
        },
        {
          "order": null,
          "start": "15:55",
          "end": "16:00",
          "type": "transition",
          "name": "⟶ 5분 (다음: 까르 - 솔로/듀오)",
          "transitionMinutes": 5,
          "nextActName": "까르"
        },
        {
          "order": 11,
          "start": "16:00",
          "end": "16:25",
          "type": "performance",
          "name": "까르",
          "scale": "solo",
          "musicianIds": [
            5
          ]
        },
        {
          "order": null,
          "start": "16:25",
          "end": "16:35",
          "type": "transition",
          "name": "⟶ 10분 (다음: 김동산과 블루이웃 - 대형밴드)",
          "transitionMinutes": 10,
          "nextActName": "김동산과 블루이웃"
        },
        {
          "order": 12,
          "start": "16:35",
          "end": "17:00",
          "type": "performance",
          "name": "김동산과 블루이웃",
          "scale": "big-band",
          "musicianIds": [
            3
          ]
        },
        {
          "order": null,
          "start": "17:00",
          "end": "17:05",
          "type": "transition",
          "name": "⟶ 5분 (다음: 삼각전파사 - 솔로/듀오)",
          "transitionMinutes": 5,
          "nextActName": "삼각전파사"
        },
        {
          "order": 13,
          "start": "17:05",
          "end": "17:30",
          "type": "performance",
          "name": "삼각전파사",
          "scale": "solo",
          "musicianIds": [
            34
          ]
        },
        {
          "order": null,
          "start": "17:30",
          "end": "17:35",
          "type": "transition",
          "name": "⟶ 5분 (다음: 자이 - 솔로/듀오)",
          "transitionMinutes": 5,
          "nextActName": "자이"
        },
        {
          "order": 14,
          "start": "17:35",
          "end": "18:00",
          "type": "performance",
          "name": "자이",
          "scale": "solo",
          "musicianIds": [
            11
          ]
        },
        {
          "order": null,
          "start": "18:00",
          "end": "18:05",
          "type": "transition",
          "name": "⟶ 5분 (다음: 정진석 - 솔로/듀오)",
          "transitionMinutes": 5,
          "nextActName": "정진석"
        },
        {
          "order": 15,
          "start": "18:05",
          "end": "18:30",
          "type": "performance",
          "name": "정진석",
          "scale": "solo",
          "musicianIds": [
            2
          ]
        },
        {
          "order": null,
          "start": "18:30",
          "end": "18:35",
          "type": "transition",
          "name": "⟶ 5분 (다음: 레인보우99 - 솔로/듀오)",
          "transitionMinutes": 5,
          "nextActName": "레인보우99"
        },
        {
          "order": 16,
          "start": "18:35",
          "end": "19:00",
          "type": "performance",
          "name": "레인보우99",
          "scale": "solo",
          "musicianIds": [
            20
          ]
        },
        {
          "order": null,
          "start": "19:00",
          "end": "19:05",
          "type": "transition",
          "name": "⟶ 5분 (다음: 조성일 - 솔로/듀오)",
          "transitionMinutes": 5,
          "nextActName": "조성일"
        },
        {
          "order": 17,
          "start": "19:05",
          "end": "19:30",
          "type": "performance",
          "name": "조성일",
          "scale": "solo",
          "musicianIds": [
            45
          ]
        },
        {
          "order": null,
          "start": "19:30",
          "end": "19:35",
          "type": "transition",
          "name": "⟶ 5분 (다음: 황명하 - 솔로/듀오)",
          "transitionMinutes": 5,
          "nextActName": "황명하"
        },
        {
          "order": 18,
          "start": "19:35",
          "end": "20:00",
          "type": "performance",
          "name": "황명하",
          "scale": "solo",
          "musicianIds": [
            56
          ]
        },
        {
          "order": null,
          "start": "20:00",
          "end": "20:05",
          "type": "transition",
          "name": "⟶ 5분 (다음: 치치 - 솔로/듀오)",
          "transitionMinutes": 5,
          "nextActName": "치치"
        },
        {
          "order": 19,
          "start": "20:05",
          "end": "20:30",
          "type": "performance",
          "name": "치치",
          "scale": "solo",
          "musicianIds": [
            49
          ]
        },
        {
          "order": null,
          "start": "20:30",
          "end": "20:35",
          "type": "transition",
          "name": "⟶ 5분 (다음: TAGI - 솔로/듀오)",
          "transitionMinutes": 5,
          "nextActName": "TAGI"
        },
        {
          "order": 20,
          "start": "20:35",
          "end": "21:00",
          "type": "performance",
          "name": "TAGI",
          "scale": "solo",
          "musicianIds": [
            60
          ]
        }
      ]
    }
  ]
};
